### ISSUE TITLE
node modules folder included

### ISSUE THREAD

**Issue by aagavin** [MavOmidK/COMP308-Lab1#1]
You need to add this folder to a .gitignore

**Comment by MavOmidK** [comment]
Lol yeah. I forgot to save my .gitignore when i pushed it. I've been looking for a way to delete it from the online repo but no luck

**Comment by MavOmidK** [comment]
My gitignore was blank* when i pushed it

**Comment by aagavin** [comment]
Try this 

`git rm -r node_modules`
`git add .`
`git commit -m 'your message'`
`git push origin 《branch name》`

**Comment by aagavin** [comment]
Then you need to run `npm install`

**Comment by aagavin** [comment]
You can do the same for the .vscode dit

**Comment by MavOmidK** [comment]
is there no way to remove a folder inside the online repo?

**Comment by aagavin** [comment]
Soft of. I'll explain tomorrow.
